# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# ID3 tag music genres are surprisingly specific.

genres = Hash[[
  "Blues",
  "Classic Rock",
  "Country",
  "Dance",
  "Disco",
  "Funk",
  "Grunge",
  "Hip-Hop",
  "Jazz",
  "Metal",
  "New Age",
  "Oldies",
  "Other",
  "Pop",
  "R&B",
  "Rap",
  "Reggae",
  "Rock",
  "Techno",
  "Industrial",
  "Alternative",
  "Ska",
  "Death Metal",
  "Pranks",
  "Soundtrack",
  "Euro-Techno",
  "Ambient",
  "Trip-Hop",
  "Vocal",
  "Jazz+Funk",
  "Fusion",
  "Trance",
  "Classical",
  "Instrumental",
  "Acid",
  "House",
  "Game",
  "Sound Clip",
  "Gospel",
  "Noise",
  "Alternative Rock",
  "Bass",
  "Soul",
  "Punk",
  "Space",
  "Meditative",
  "Instrumental Pop",
  "Instrumental Rock",
  "Ethnic",
  "Gothic",
  "Darkwave",
  "Techno-Industrial",
  "Electronic",
  "Pop-Folk",
  "Eurodance",
  "Dream",
  "Southern Rock",
  "Comedy",
  "Cult",
  "Gangsta",
  "Top 40",
  "Christian Rap",
  "Pop/Funk",
  "Jungle",
  "Native US",
  "Cabaret",
  "New Wave",
  "Psychadelic",
  "Rave",
  "Showtunes",
  "Trailer",
  "Lo-Fi",
  "Tribal",
  "Acid Punk",
  "Acid Jazz",
  "Polka",
  "Retro",
  "Musical",
  "Rock & Roll",
  "Hard Rock",
  "Folk",
  "Folk-Rock",
  "National Folk",
  "Swing",
  "Fast Fusion",
  "Bebob",
  "Latin",
  "Revival",
  "Celtic",
  "Bluegrass",
  "Avantgarde",
  "Gothic Rock",
  "Progressive Rock",
  "Psychedelic Rock",
  "Symphonic Rock",
  "Slow Rock",
  "Big Band",
  "Chorus",
  "Easy Listening",
  "Acoustic",
  "Humour",
  "Speech",
  "Chanson",
  "Opera",
  "Chamber Music",
  "Sonata",
  "Symphony",
  "Booty Bass",
  "Primus",
  "Porn Groove",
  "Satire",
  "Slow Jam",
  "Club",
  "Tango",
  "Samba",
  "Folklore",
  "Ballad",
  "Power Ballad",
  "Rhythmic Soul",
  "Freestyle",
  "Duet",
  "Punk Rock",
  "Drum Solo",
  "Acapella",
  "Euro-House",
  "Dance Hall",
  "Goa",
  "Drum & Bass",
  "Club - House",
  "Hardcore",
  "Terror",
  "Indie",
  "BritPop",
  "Negerpunk",
  "Polsk Punk",
  "Beat",
  "Christian Gangsta Rap",
  "Heavy Metal",
  "Black Metal",
  "Crossover",
  "Contemporary Christian",
  "Christian Rock",
  "Merengue",
  "Salsa",
  "Thrash Metal",
  "Anime",
  "JPop",
  "Synthpop"
].map { |genre| [genre, Genre.find_or_create_by(name: genre)] }]

artists = Hash[[
  "Britnet Spears",
  "Maria Carey",
  "Jay Z",
  "Beyonce",
  "The Weekend",
  "Ed Sheeran",
  "Toto",
  "Journey",
  "Bon Jovi",
  "Bonnie Tyler",
  "Men At Work",
  "Queen",
  "Kansas",
  "Nirvana",
  "Billy Joel",
  "Aerosmith",
  "Phil Colin",
  "John Legend",
  "Chicago",
  "Muse",
  "Foreigner",
  "Coldplay",
  "Gorillaz",
  "Daft Punk"
].map { |artist| [artist, Artist.find_or_create_by(name: artist)] }]

Song.create(title: "Happy Day", artist_id: 1, genre_id: 1)
Song.create(title: "Warning", artist_id: 2, genre_id: 1)
Song.create(title: "Good Morning", artist_id: 3, genre_id: 2)
Song.create(title: "Water In Me", artist_id: 5, genre_id: 7)
Song.create(title: "Cry Over You", artist_id: 9, genre_id: 4)
Song.create(title: "Make Yourself", artist_id: 3, genre_id: 7)
Song.create(title: "Never See You Again", artist_id: 10, genre_id: 4)
Song.create(title: "Goodbye", artist_id: 6, genre_id: 14)
Song.create(title: "Where Are You", artist_id: 9, genre_id: 18)
Song.create(title: "Hand In Hand", artist_id: 3, genre_id: 3)

Note.create(content: "none", song_id: 1)
Note.create(content: "junk", song_id: 3)
Note.create(content: "bit", song_id: 2)
Note.create(content: "funk", song_id: 6)
Note.create(content: "another", song_id: 8)
